/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jni_demo_TestJNI */

#ifndef _Included_com_github_jni_demo_TestJNI
#define _Included_com_github_jni_demo_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jni_demo_TestJNI
 * Method:    HelloWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_jni_1demo_TestJNI_HelloWord
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
